apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: p-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: akash1gupta/order-05:latest
          ports:
            - containerPort: 3405
