apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: p-microservices
spec:
  type: LoadBalancer
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3406
